### ISSUE TITLE
Front Panel Menu System for the WLAN Pi OLED display Failed to start

### ISSUE THREAD

**Issue by jmack778** [WLAN-Pi/wlanpi-fpms#110]
I updated my WLANPi today and after the reboot the front panel menu system no longer stays on and upon restarting the service 
 it fails.  Attached are the log entries received, any recommendations to correct this?  Currently the FPMS isn't working..

/lib/systemd/system/wlanpi-fpms.service

Requires
-.mountsysinit.targetsystem.slice
Wanted by
multi-user.target
Conflicts
shutdown.target
Before
multi-user.targetshutdown.target
After
-.mountbasic.targetsysinit.targetsystem.slicesystemd-journald.socketwlanpi-rename-at-startup.service

Log Results:

January 24, 2024
4:45 PM
wlanpi-fpms.service: Failed with result 'exit-code'.
systemd
4:45 PM
wlanpi-fpms.service: Main process exited, code=exited, status=1/FAILURE
systemd
4:45 PM
RuntimeError: Failed to add edge detection
fpms
4:45 PM
GPIO.add_event_detect(
fpms
4:45 PM
File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/pins/rpigpio.py", line 226, in _enable_event_detect
fpms
4:45 PM
self._enable_event_detect()
fpms
4:45 PM
File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/pins/pi.py", line 319, in _set_when_changed
fpms
4:45 PM
lambda self, value: self._set_when_changed(value),
fpms
4:45 PM
File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/pins/__init__.py", line 432, in <lambda>
fpms
4:45 PM
self.pin.when_changed = self._pin_changed
fpms
4:45 PM
File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/input_devices.py", line 171, in __init__
fpms
4:45 PM
super(HoldMixin, self).__init__(*args, **kwargs)
fpms
4:45 PM
File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/mixins.py", line 433, in __init__
fpms
4:45 PM
super(Button, self).__init__(
fpms
4:45 PM
File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/input_devices.py", line 414, in __init__
fpms
4:45 PM
self = super(GPIOMeta, cls).__call__(*args, **kwargs)
fpms
4:45 PM
File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/devices.py", line 108, in __call__
fpms
4:45 PM
button_down = GPIO_Button(BUTTONS_PINS['down'])
fpms
4:45 PM
File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/fpms.py", line 960, in main
fpms
4:45 PM
sys.exit(fpms.main())
fpms
4:45 PM
File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/__main__.py", line 3, in <module>
fpms
4:45 PM
from fpms.__main__ import main
fpms
4:45 PM
File "/usr/sbin/fpms", line 5, in <module>
fpms
4:45 PM
Traceback (most recent call last):
fpms
4:45 PM
--------------------------------------------------
fpms
4:45 PM
Mode: RGB
fpms
4:45 PM
Dimensions: 128 x 128
fpms
4:45 PM
Interface: spi
fpms
4:45 PM
Display: ssd1351
fpms
4:45 PM
Version: luma.oled 3.9.0 (luma.core 2.4.0)
fpms
4:45 PM
--------------------------------------------------
fpms
4:45 PM
Started Front Panel Menu System for the WLAN Pi OLED display.

![WLANPi Front Panel Menu Failure Summary - 1-24-24 - 2](https://github.com/WLAN-Pi/wlanpi-fpms/assets/157653836/2f4a5639-7a29-41cb-8030-8e39ac6e9d33)
![WLANPi Front Panel Menu Failure Logs - 1-24-24 - 2](https://github.com/WLAN-Pi/wlanpi-fpms/assets/157653836/811ce46f-aab3-40af-a270-2b4ce6d8ecf9)
![WLANPi Front Panel Menu Failure Logs - 1-24-24](https://github.com/WLAN-Pi/wlanpi-fpms/assets/157653836/8711c8f8-3f09-4abb-9ac5-03f93fc32556)

**Comment by joshschmelzle** [comment]
Closing due to being resolved based on https://github.com/WLAN-Pi/wlanpi-fpms/issues/76#issuecomment-1909135457. Updated FPMS version fixes with newer kernel.
